apiVersion: v1
kind: ConfigMap # 配置
metadata:
  name: nginx-laravel-config
data:
  config: |-
    server {
      listen 8081;
      location / {
        root   /var/www/laravel/public;
        index  index.html index.htm;
      }
    }
