apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1 # 副本数量
  strategy: # 部署策略
    type: RollingUpdate # 滚动更新
    rollingUpdate: # 滚动更新参数
      maxSurge: 1 # 更新过程中同时在线最大 Pods 数量
      maxUnabailable: 0 # 更新过程中不可用过的最大 Pods 数量
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel # 容器名称
          image: # 镜像
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql-service # 注意，这个值需要和之前设置的 mysql service 的名称保持一致
            - name: REDIS_HOST
              value: redis-service # 同上

---

apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  selector:
    app:laravel
  ports:
    - port: 80 # 暴露的端口
      targetPort: 80 # 目标容器的端口