apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8081
          volumeMounts: # 挂载配置
          - name: nginx-php-config # 挂载名
            mountPath: /etc/nginx/conf.d/php.conf # 指定容器内对应的挂载点，也就是将挂载名对应的内容挂载到容器内这个设定的挂载点
            subPath: php.conf
      volumes:
        - name: nginx-php-config # 挂载名
          configMap:
            name: nginx-config # 将 name=config 的 configMap 配置加载
            items:
              - key: config
                path: php.conf



--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: # 拥有 app=nginx label 的 pod 属于该 service，也就是上面定义的 pod
    app: nginx
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080 # 定义外部访问， 测试
  type: NodePort # 通过 nodeIp:nodePort 访问